export const categoryList = [
  'national',
  'politics',
  'international',
  'sports',
  'culture-and-entertainment',
  'economy',
  'crime',
  'health',
  'election',
  'education',
  'local-news',
  'capital',
  'lifestyle',
  'environment',
  'tourism',
  'feature',
  'special-report',
  'opinion',
  'country-news',
  'law-justice',
  'entertainment',
  'job',
  'others',
];


